//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class veterclinicEntities : DbContext
    {
        public veterclinicEntities()
            : base("name=veterclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal_types> animal_types { get; set; }
        public virtual DbSet<breeds> breeds { get; set; }
        public virtual DbSet<medicine_stocks> medicine_stocks { get; set; }
        public virtual DbSet<medicines> medicines { get; set; }
        public virtual DbSet<notifications> notifications { get; set; }
        public virtual DbSet<owners> owners { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<prescriptions> prescriptions { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visits> visits { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> AddVisit(Nullable<int> patient_id, Nullable<int> user_id, string diagnosis, string symptoms, Nullable<decimal> temperature, Nullable<decimal> weight, string recommendations)
        {
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("patient_id", patient_id) :
                new ObjectParameter("patient_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var diagnosisParameter = diagnosis != null ?
                new ObjectParameter("diagnosis", diagnosis) :
                new ObjectParameter("diagnosis", typeof(string));
    
            var symptomsParameter = symptoms != null ?
                new ObjectParameter("symptoms", symptoms) :
                new ObjectParameter("symptoms", typeof(string));
    
            var temperatureParameter = temperature.HasValue ?
                new ObjectParameter("temperature", temperature) :
                new ObjectParameter("temperature", typeof(decimal));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("weight", weight) :
                new ObjectParameter("weight", typeof(decimal));
    
            var recommendationsParameter = recommendations != null ?
                new ObjectParameter("recommendations", recommendations) :
                new ObjectParameter("recommendations", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("AddVisit", patient_idParameter, user_idParameter, diagnosisParameter, symptomsParameter, temperatureParameter, weightParameter, recommendationsParameter);
        }
    
        public virtual ObjectResult<GetLowStockMedicines_Result> GetLowStockMedicines(Nullable<int> threshold)
        {
            var thresholdParameter = threshold.HasValue ?
                new ObjectParameter("threshold", threshold) :
                new ObjectParameter("threshold", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLowStockMedicines_Result>("GetLowStockMedicines", thresholdParameter);
        }
    
        public virtual ObjectResult<GetPatientHistory_Result> GetPatientHistory(Nullable<int> patient_id)
        {
            var patient_idParameter = patient_id.HasValue ?
                new ObjectParameter("patient_id", patient_id) :
                new ObjectParameter("patient_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPatientHistory_Result>("GetPatientHistory", patient_idParameter);
        }
    }
}
