//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine_stocks
    {
        public int id { get; set; }
        public int medicine_id { get; set; }
        public int quantity { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
    
        public virtual medicines medicines { get; set; }
    }
}
