//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifications
    {
        public int id { get; set; }
        public int medicine_id { get; set; }
        public string message { get; set; }
        public System.DateTime created_date { get; set; }
        public bool is_read { get; set; }
    
        public virtual medicines medicines { get; set; }
    }
}
