//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patients()
        {
            this.visits = new HashSet<visits>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int owner_id { get; set; }
        public int animal_type_id { get; set; }
        public Nullable<int> breed_id { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string color { get; set; }
        public string distinctive_features { get; set; }
        public string avatar_path { get; set; }
        public string chip_number { get; set; }
    
        public virtual animal_types animal_types { get; set; }
        public virtual breeds breeds { get; set; }
        public virtual owners owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visits> visits { get; set; }
    }
}
