//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescriptions
    {
        public int id { get; set; }
        public int visit_id { get; set; }
        public int medicine_id { get; set; }
        public string dosage { get; set; }
        public string frequency { get; set; }
        public int duration_days { get; set; }
        public int quantity { get; set; }
    
        public virtual medicines medicines { get; set; }
        public virtual visits visits { get; set; }
    }
}
