//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visits()
        {
            this.prescriptions = new HashSet<prescriptions>();
        }
    
        public int id { get; set; }
        public int patient_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime visit_date { get; set; }
        public string diagnosis { get; set; }
        public string symptoms { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string recommendations { get; set; }
        public Nullable<System.DateTime> next_visit_date { get; set; }
        public string status { get; set; }
    
        public virtual patients patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescriptions> prescriptions { get; set; }
        public virtual users users { get; set; }
    }
}
